### PR TITLE
Fix : Updated code as per super class concept

### LINKED ISSUE #2: Bug: Connection to MongoDB failed
There seems to be a bug due to which connection to MongoDB cannot be established. All the **GET/POST** requests are hitting the server but I don't seem to get a response or sometimes I get a response with a **500 error**. Any help will be appreciated.

### PR DESCRIPTION
**Pull request by Tanmay000009**
#2 
URI is to be set in the superclass. So instead of this.URI, super.URI should be used. Accordingly, for other inherited variables with the same issue, updated this to super.

### CODE REVIEW

File: app/src/main/java/com/arjun1407/dbkong/database/mongodb/MongoDBConnect.java [hunk 1]
```diff
@@ -7,7 +7,7 @@
     private static MongoDBConnect instance;
 
     public MongoDBConnect(String uri) {
-        this.uri = uri;
+        super.uri = uri;
```
Comment (1407arjun) [inline app/src/main/java/com/arjun1407/dbkong/database/mongodb/MongoDBConnect.java:10]: Learnt how the super class inheritance works ! 👍

**Comment by 1407arjun** [comment]
I think this should fix the issue 👍
